// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const getEnv = (key: string) => {
  const val = import.meta.env[key];
  return val ? val.trim() : "";
};

const SUPABASE_URL = getEnv("VITE_SUPABASE_URL") || "https://placeholder-url.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = getEnv("VITE_SUPABASE_PUBLISHABLE_KEY") || "placeholder-key";

console.log("Supabase Client Init:");
console.log("- URL:", SUPABASE_URL);
console.log("- Key Length:", SUPABASE_PUBLISHABLE_KEY.length);
console.log("- Key Start:", SUPABASE_PUBLISHABLE_KEY.substring(0, 10));

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});